<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function form_examples_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['name']['#description'] = t('Enter your username, as assigned by IT.');
    $form['pincode'] = [
      '#type' => 'password',
      '#title' => t('PIN Code'),
      '#description' => t('Enter your super-secret PIN code.'),
      '#required' => TRUE,
    ];
    $form['#validate'][] ='form_examples_check_pin';
    $form['#submit'][] = 'form_examples_log_logins';
  }
}

function form_examples_check_pin($form, FormStateInterface $form_state) {
  $pin = $form_state->getValue('pincode');
  if (empty($pin) || $pin != '1234') {
    $form_state->setErrorByName('pincode', t('Invalid PIN code.'));
  }
}

function form_examples_log_logins($form, FormStateInterface $form_state) {
  \Drupal::messenger()->addMessage(t('Your login as been logged for reference.'));
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function form_examples_form_node_article_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form['promote']['#access'] = FALSE;
  $form['sticky']['#access'] = FALSE;
}