<?php

function route_examples_menu_links_discovered_alter(&$links) {
  $links['entity.user.collection']['title'] = t('Users');
}

function route_examples_menu_local_actions_alter(&$local_actions) {
  $local_actions['node.add_page']['title'] = t('Add new node');
}

function route_examples_menu_local_tasks_alter(&$data, $route_name) {
  if ($route_name == 'user.login') {
    $data['tabs'][0]['user.login']['#link']['title'] = t('Sign in');
  }
}
